zero_zero_homepage:
    path:     /index
    defaults: { _controller: ZeroZeroBundle:Default:index }
zero_zero_characters:
    path:     /characters
    defaults: { _controller: ZeroZeroBundle:Default:characters }
zero_zero_show_characters:
    path:     /character/{id}
    defaults: { _controller: ZeroZeroBundle:Default:showCharacter }
zero_zero_books:
    path:     /books
    defaults: { _controller: ZeroZeroBundle:Default:books }

